export default {
    GET_CATEGORY_ONLINE: '[CATEGORY] GET_CATEGORY_ONLINE',
    GET_CATEGORY_ONLINE_RESULT: '[CATEGORY] GET_CATEGORY_ONLINE_RESULT',
    GET_LIST_CATEGORY: '[CATEGORY] GET_LIST_CATEGORY',
    GET_LIST_CATEGORY_RESULT: '[CATEGORY] GET_LIST_CATEGORY_RESULT',

    TYPE_GET_CATEGORY: 'get_category'
}
