<?php
/**
 * Copyright © 2018 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magestore\Webpos\Block\Adminhtml\Pos\Tab\SessionDetail $block */
?>
<fieldset class="fieldset admin__fieldset" id="admin_webpos_session_detail"
          data-bind="scope:'admin_webpos_session_detail'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</fieldset>
<div id="admin_webpos_close_session_popup" data-bind="scope:'admin_webpos_close_session_popup'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<div id="admin_webpos_cash_activity_popup" data-bind="scope:'admin_webpos_cash_activity_popup'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<div id="admin_webpos_cash_adjustment_popup" data-bind="scope:'admin_webpos_cash_adjustment_popup'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<div id="admin_webpos_cash_set_closing_balance_reason" data-bind="scope:'admin_webpos_cash_set_closing_balance_reason'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<iframe id="webpos_pos_session_print_iframe" allowtransparency="true" frameborder="0" name="webpos_pos_print_iframe"
        style="width: 100%; background-color:transparent; display:none;"
        src="">
</iframe>
<script>
    window.POSConfig = <?php echo \Zend_Json::encode($block->getPOSConfig()); ?>;
    require(["Magestore_Webpos/js/model/pos/session_detail/management"], function (PosManagement) {
        PosManagement.initData('<?php echo $block->getShiftData() ?>');
    });
</script>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components" : {
                "admin_webpos_session_detail": {
                    "component": "Magestore_Webpos/js/view/pos/session_detail/detail",
                    "displayArea": "admin_webpos_session_detail"
                }
            }
        }
    }
}
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>